dataSource:
  ds_pinterest-test: !!org.apache.commons.dbcp2.BasicDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1k5i9g0iyt2jc79o.mysql.rds.aliyuncs.com:3306/pinterest-test?useSSL=false
    username: root
    password: zxcasdqwe123!@#
    maxTotal: 2
    maxIdle: 2
    minIdle: 1
    initialSize: 1
   
  ds_default: !!org.apache.commons.dbcp2.BasicDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1k5i9g0iyt2jc79o.mysql.rds.aliyuncs.com:3306/neptune_default?useSSL=false
    username: root
    password: zxcasdqwe123!@#
    maxTotal: 2
    maxIdle: 2
    minIdle: 1
    initialSize: 1

    
  ds_jhk-user-imgs: !!org.apache.commons.dbcp2.BasicDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1k5i9g0iyt2jc79o.mysql.rds.aliyuncs.com:3306/jhk-user-imgs-test?useSSL=false
    username: root
    password: zxcasdqwe123!@#
    maxTotal: 2
    maxIdle: 2
    minIdle: 1
    initialSize: 1


   
defaultDataSourceName: ds_default

tables:
   sequence_pin_next_id: 
     actualTables: ds_default.sequence_pin_next_id

  # ds_pinterest
   board:
     actualTables: ds_pinterest-test.board
     databaseStrategy :
       shardingColumns : none
       algorithmClassName : com.dangdang.ddframe.rdb.sharding.api.strategy.database.NoneDatabaseShardingAlgorithm
     tableStrategy :
       shardingColumns : none
       algorithmClassName : com.dangdang.ddframe.rdb.sharding.api.strategy.table.NoneTableShardingAlgorithm

# ds_jhk-user-imgs
   user_board_favourite: 
     actualTables: ds_jhk-user-imgs.user_board_favourite
     databaseStrategy : 
       shardingColumns : none
       algorithmClassName : com.dangdang.ddframe.rdb.sharding.api.strategy.database.NoneDatabaseShardingAlgorithm
     tableStrategy : 
       shardingColumns : none
       algorithmClassName : com.dangdang.ddframe.rdb.sharding.api.strategy.table.NoneTableShardingAlgorithm


props: 
  metrics.enable: false
  sql.show: false
  executor.min.idle.size: 20
  executor.max.size: 50